[package]
name = "docker-autoheal"
version = "0.3.2"
authors = ["Travis M Knight <travis.knight@tmknight.net>"]
license = "MIT"
description = "Monitor and restart unhealthy docker containers"
readme = "README.md"
homepage = "https://github.com/tmknight/docker-autoheal"
edition = "2021"
rust-version = "1.74.1"

[dependencies]
bollard = "*"
chrono = "0.4.*"
futures = "0.3.*"
rustls = "0.22.*"
tokio = { version = "1.*", features = ["full"] }
getopts = "0.2.*"

[[bin]]
name = "docker-autoheal"
bench = true
test = true
