[package]
name = "docker-autoheal"
version = "0.2.1"
authors = ["Travis M Knight <travis.knight@tmknight.net>"]
license = "MIT"
description = "Monitor and restart unhealthy docker containers"
readme = "README.md"
homepage = "https://github.com/tmknight/docker-autoheal"
edition = "2021"
rust-version = "1.74.1"

[dependencies]
bollard = "*"
chrono = "*"
futures = "*"
tokio = { version = "*", features = ["full"] }

[[bin]]
name = "docker-autoheal"
bench = false
test = false
