name: "Cargo Check"

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - 'examples/**'
      - 'docker/**'
      - 'test/**'
      - '*.md'
      - '.*'
      - '*.lock'
      - '.LICENSE'
    branches: [ "main", "develop" ]
#  pull_request:
#    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check
    - name: Clippy
      run: cargo clippy -- -D warnings
