name: "Git Tag"

on:
  workflow_dispatch:
  # push:
  #   paths-ignore:
  #     - '.github/**'
  #     - 'examples/**'
  #     - 'docker/**'
  #     - 'test/**'
  #     - '*.md'
  #     - '.*'
  #     - '*.lock'
  #     - '.LICENSE'
  #   branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml

  create-tag:
    name: "Create tag"
    runs-on: "ubuntu-latest"
    needs: get-version
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Set Tag"
        shell: "bash"
        run: |
          git tag ${{ needs.get-version.outputs.pkg-version }} && git push --tags
